### PR TITLE
Add demo election content

### LINKED ISSUE #28: Demo content module
To make it easier for people to test it would be nice to have a demo content module that would create some example election results.

### PR DESCRIPTION
**Pull request by stephen-cox**
Fixes #28

### CODE REVIEW

**Comment by markconroy** [comment]
@stephen-cox this looks great, but is also creating duplicate taxonomy terms for anyone who already has the `localgov_elections_uk_parties` module installed.

Do you think we could get this to use the UK Parties module for the taxonomy terms instead of generating new ones? Or, failing that, delete the generated nodes/terms when uninstalling this module?

Screenshot 2024-06-20 at 16 41 28

**Comment by finnlewis** [comment]
note: want to check if we can remove the content when uninstalling the module

**Comment by finnlewis** [comment]
@markconroy I've added '(demo content' to the term labels for now. 

image

Looks like there is a drush command in the pipeline to remove content on uninstall, see https://www.drupal.org/project/default_content/issues/3282547

For now there is not much content, so I think it would be easy enough to remove the demo content if desired.

**Review by finnlewis — APPROVED** [review]
Makes it so much easier to test, thanks @stephen-cox !

**Comment by finnlewis** [comment]
Not sure why the tests are getting a 500 server error here, they all still pass locally.

**Pull request merged**
