### PR TITLE
renames modules fields entities

### LINKED ISSUE #1: Rename parent module to localgov_elections
Coming from https://github.com/localgovdrupal/localgov_elections/issues/11

### PR DESCRIPTION
**Pull request by markconroy**
Closes #1 

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

### CODE REVIEW

**Comment by finnlewis** [comment]
Very cool, thanks @markconroy , testing now.

**Comment by markconroy** [comment]
@finnlewis Don't test, it's not ready yet. Nearly there.

**Review by finnlewis — APPROVED** [review]
This is now working for @markconroy  and me locally, so merging in to then publish on packagist. Thanks @markconroy !

**Comment by willguv** [comment]
Top work, thank you!

**Pull request merged**
