### PR TITLE
Fix: Account for deleted parties

### LINKED ISSUE #37: Deleted party causes WSOD
Reproduction steps:
1. Added a few new parties.
2. Added a new election.
3. Attached the parties from step 1 to the election from step 2.
4. Election page loads okay.
5. Deleted one or more parties from step 1.
6. Attempts to reload the election page results in WSOD (White screen of death) :(

### PR DESCRIPTION
**Pull request by Adnan-cds**
Account for the possibility that one or more electoral parties could be deleted.  This is particularly a possibility during testing and training.

Resolved #37

### CODE REVIEW

**Comment by dedavidson** [comment]
I'm not comfortable with this approach as it means a taxonomy term could be deleted and impact a historical election. I think it is much better to prevent deletion if a term is in use.

**Comment by Adnan-cds** [comment]
> I think it is much better to prevent deletion if a term is in use.

Good morning :)  I think that's somewhat of a feature request which can be implemented in a different ticket.  What I have done in this change is to apply some defensive programming to prevent WSOD when Editors are practising to get a taste of this module.

**Review by finnlewis — APPROVED** [review]
I think this is the right way to prevent the wsod in the case where we delete party terms.

**Comment by finnlewis** [comment]
> I think it is much better to prevent deletion if a term is in use.

@dedavidson let's track that here https://github.com/localgovdrupal/localgov_elections/issues/75

**Comment by Adnan-cds** [comment]
Thanks.  Merging...

**Pull request merged**
