### PR TITLE
Prevent localgov_election_candidate paragraphs from generating new re…

### PR DESCRIPTION
**Pull request by finnlewis**
…visions.

See #94 

Please test this! 

Steps to reproduce the original bug: 

https://github.com/localgovdrupal/localgov_elections/issues/94#issuecomment-2206127506

With this small change, localgov_election_candidate paragraphs should not generate new revisions, so the duplicate revision creation is averted.

This mitigates the bug and prevents random data displaying, but still means revisions does not work.

### CODE REVIEW

**Comment by chriswales95** [comment]
@finnlewis Just going to review now.

If this is a permanent fix, I'd like to see 49a75fa865ce4298c7924c875ceca8c3a3880aab reverted as part of this.

**Comment by finnlewis** [comment]
@chriswales95 good call! 

I think we update the README to explain that revisions does not currently work. I'll look now.

**Comment by chriswales95** [comment]
@finnlewis Okay, I tested and yes I no longer get the funny graphs but yeah the paragraph revisions don't work. So you can change a vote, revert the area vote revision, and the vote amount is still the old value.

Much better than before @finnlewis! 

Any ideas on how we'd fully support revisions?

**Review by chriswales95 — APPROVED** [review]

**Comment by markconroy** [comment]
This PR is working for me to stop the funny chart.

**Pull request merged**
