### PR TITLE
Fix issue with demo content taxonomy names

### LINKED ISSUE #91: Candidate saving breaks if party taxonomy title has a bracket in it
Raised by @finnlewis in https://github.com/localgovdrupal/localgov_elections/issues/88

> Possibly related: editing the results of an area does not allow me to save.
> 
> Steps to reproduce:
> 
>     Install fresh localgov profile,
>     enable localgov_elections_demo_content,
>     edit an area (eg https://localgov.ddev.site/node/2/edit) and amend the vote count for one of the results, save.
>     Error message: The referenced entity (taxonomy_term: demo content) does not exist.
>     And I cannot save the area.
> 
> Tried toggling the finalised votes to off too. Same behaviour.

This means the demo content module is broken as well.

I think we should:

1. Remove the brackets from the names of demo content
2. Add some validation to ensure brackets cannot be entered

### PR DESCRIPTION
**Pull request by chriswales95**
Should close #91.

What this PR does:

1. Removes brackets from demo content party names
2. Adds warning to taxonomy page for party name in party taxonomy page
3. Adds warning to candidate party autocomplete field widget
4. Adds a patch so the help text appears on autocomplete deluxe widget

### CODE REVIEW

**Comment by finnlewis** [comment]
This reverts a commit I made to rename the demo content taxonomy names:  https://github.com/localgovdrupal/localgov_elections/commit/dae0f9fbd76c16167102ea04b41ab8aed5ba2caf

This was done because people testing were confused about the duplicate parties when enabling the demo content and the UK parties module. 

I can't find the original issue, maybe it was in Slack? 

Either way, I think we need a way for user to distinguish between demo taxonomy terms and those generated by the UK parties module. 

But more fundamentally, I wonder why are brackets a problem in taxonomy term names in this instance.

**Comment by chriswales95** [comment]
@finnlewis Ah I wasn't aware.

Basically, entity references fields usally have stuff in the form `entity title (entity id)`. It must do some pattern matching with the brackets. When I looked in xdebug in the form state, it had arrays in the form of (just making this up but it's close enough) `[ field_value => [ "target_id" => "demo content"] ]` for taxonomy names like "Labour (demo content)".

Mabye square brackets would work?

**Comment by markconroy** [comment]
Handiest might be to change the names to `Labour - demo content` instead of `Labour (demo content)`

**Comment by chriswales95** [comment]
@markconroy That's sensible. I'll make the change soon.

**Comment by chriswales95** [comment]
I did try and do some validation in the form validation hook but could not get the full text from the input :/. It would be good to revisit that at some point as well.

**Comment by chriswales95** [comment]
@markconroy @finnlewis @dedavidson Switched to using the dashes. @finnlewis this should fix your problem.

**Comment by finnlewis** [comment]
Testing, thanks @chriswales95 !

**Review by finnlewis — APPROVED** [review]
Works better now, thanks @chriswales95 !

**Pull request merged**
