### PR TITLE
Fix: Results heading on the Summary page

### LINKED ISSUE #72: Election summary page is using a hardcoded label for results
The Election summary page is using a [hardcoded label](https://github.com/localgovdrupal/localgov_elections/blob/2bbeb610f133c71bf01a22ad062867f0d3eb3c30/config/install/views.view.localgov_election_results.yml#L1377) for results.

How to reproduce:
- Create a National Parliamentary election.
- Open the summary page of this new election.
- Look for the results.
- The results heading says "Ward results".

### PR DESCRIPTION
**Pull request by Adnan-cds**
Varies the results heading depending on the type of the election.

How to reproduce:
- Create a *National Parliamentary* election.
- Open the summary page of this new election.
- Look for the results.
- The results heading says "Ward results".

This change fixes the wording of the heading to say *National Parliamentary results*, *Parish results* and so on.

Resolves #72

### CODE REVIEW

**Comment by willguv** [comment]
Hi Adnan, thanks for making this change. Is it possible to use other words here?

We could use "Constituency results" for example

Not sure on wording for other election types but we could review 

Please let me know what you think

**Comment by Adnan-cds** [comment]
> Is it possible to use other words here?

Hi Will, these wordings are coming from the "Type of election" dropdown of the Election type nodes: 
image

These wordings are defined in a [config file](https://github.com/localgovdrupal/localgov_elections/blob/ab3e741e9e91d628f126e70131d3ff0844295e05/config/install/field.storage.node.localgov_election_type.yml#L30) bundled with this module.  So yes, we should be able to modify these wordings if necessary.

**Comment by willguv** [comment]
The type of election in this case is National Parliamentary, but the division is a constituency. Is it possible to leave the type name as it is and change the 'ward results' wording?

**Comment by Adnan-cds** [comment]
> Is it possible to leave the type name as it is

Done.

**Comment by chriswales95** [comment]
Hi @Adnan-cds, makes sense to me. Two things:

1. is there an issue for this or something in a project somewhere?
2. Do you think we might need a test for this?

**Review by chriswales95 — COMMENTED** [review]
Hi @Adnan-cds, makes sense to me. Two things:

1. is there an issue for this or something in a project somewhere?
2. Do you think we might need a test for this?

**Comment by Adnan-cds** [comment]
> Two things:
1. I have just raised #72 
2. I have added a [simple one](https://github.com/localgovdrupal/localgov_elections/blob/fix/election-results-title/tests/src/Functional/ElectionSummaryTest.php).

**Review by chriswales95 — APPROVED** [review]
Sweet. Thanks @Adnan-cds !

**Pull request merged**
