### PR TITLE
comments out results timeline

### PR DESCRIPTION
**Pull request by markconroy**
This PR just comments out the results timeline items and disables the view. 

We can reverse this once we figure out what we actually want from the timeline feature.

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

### CODE REVIEW

**Comment by finnlewis** [comment]
Coding standards and tests need some love!

**Comment by markconroy** [comment]
@finnlewis new version now - I deleted the items instead of commenting them out. We can easily find them again in the git history.

**Comment by finnlewis** [comment]
Merge conflict @markconroy

**Comment by markconroy** [comment]
@finnlewis Back atchya

**Comment by dedavidson** [comment]
This isn't going to work for the only existing user of elections who have a historic election done on the original version that needs migrated to the new one. I would propose instead taking the approach @chriswales95 did in #84

**Comment by markconroy** [comment]
Closing in favour of https://github.com/localgovdrupal/localgov_elections/pull/87

**Pull request closed without merging**
