### PR TITLE
Fix: Election officer permissions

### PR DESCRIPTION
**Pull request by Adnan-cds**
Election officer should be able to create Areas i.e. should be able to fetch boundary data.

### Reproduction steps
- Login as an Election officer.
- Open the "Add areas" tab of an existing election from /node/NODE-ID/boundary-fetch
- Rather than listing the boundary sources, it simply says `The page you are looking for is no longer available. The information may have been removed as it was out of date.`

### CODE REVIEW

**Comment by markconroy** [comment]
Thanks @Adnan-cds 

This works fine as long as we have a boundary source set. If there is no boundary source set, we get these messages:

Screenshot 2024-06-26 at 10 29 45
Screenshot 2024-06-26 at 10 29 51

I have 2 questions:

1. Should this permission only be given if the boundary source module is enabled?
2. Should the Elections officer role also have "Administer boundary source" permission?

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

**Comment by Adnan-cds** [comment]
Thanks for trying this Mark.

> Should this permission only be given if the boundary source module is enabled?

It may be possible to dynamically assign this permission when the very first boundary source plugin is enabled.  But I don't see any advantage to that.

> Should the Elections officer role also have "Administer boundary source" permission?

This I don't know :(  Something for Finn and Will to think about may be? Copying @finnlewis @willguv

**Comment by markconroy** [comment]
Thanks Adnan, let's make this as approved and if we need that extra permission we can file a follow up for it.

**Review by markconroy — APPROVED** [review]

**Comment by Adnan-cds** [comment]
Okay, thanks for the approval.  I am merging.  Also thanking David Asch @DavidBAsch who pointed out the issue earlier.

**Pull request merged**
