### PR TITLE
Show votes only when finalised

### LINKED ISSUE #69: Votes in Summary Ward Results table always show after votes finalised
If votes are finalised then that is reversed. The votes in the Summary4 ward results table will continue to show.

### PR DESCRIPTION
**Pull request by dedavidson**
Enter some results, finalise the vote, save and then reverse the final vote, save, the votes will continue to show on Ward Results table on Summary page. This fixes it.

### CODE REVIEW

**Comment by chriswales95** [comment]
@dedavidson I think you said earlier this wasn't quite ready. Maybe should mark as draft?

**Review by chriswales95 — COMMENTED** [review]
Marking reviewed for now until it's finished.

**Comment by finnlewis** [comment]
What's left to do on this one @dedavidson ?

**Comment by dedavidson** [comment]
Its whether it needs an update hook to update the view for those already installed.

**Comment by finnlewis** [comment]
We could just explain in the release notes how to update the view, it looks fairly straight forward.

**Pull request merged**
